### ISSUE TITLE
[feature request] Add individual levels

### ISSUE THREAD

**Issue by shenef** [GB127/SRC-statistics#66]

**Comment by GB127** [comment]
This should do. Can you confirm it worked? I don't have a username with individual level runs.

**Comment by shenef** [comment]
Results in an error:
```speedrun.com statistics fetcher, program written by Niamek
Who? shenef
Fetching Shenef's data...
Initializing PBs data
Initializing Boktai: The Sun is in Your Hand - Any%'s leaderboard data
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    user = user(input("Who? "))
  File "F:\_PROGRAMS\SRC-Statistics\user.py", line 22, in __init__
    self.PBs = PBs(get_PBs(ID))
  File "F:\_PROGRAMS\SRC-Statistics\PBs.py", line 12, in __init__
    self.data.append(PB(pb))
  File "F:\_PROGRAMS\SRC-Statistics\PBs.py", line 79, in __init__
    self.leaderboard = leaderboard(self.IDs, self.game, self.category, self.place)
  File "F:\_PROGRAMS\SRC-Statistics\leaderboard.py", line 45, in __init__
    infos = get_leaderboard2(IDs)["data"]["runs"]
  File "F:\_PROGRAMS\SRC-Statistics\api.py", line 34, in get_leaderboard2
    rep = requester(f"/leaderboards/{IDs[0]}/category/{IDs[1]}" + varistr)
  File "F:\_PROGRAMS\SRC-Statistics\api.py", line 135, in requester
    raise BaseException(f"Please report this, {rep.status_code} - {URL}{link}\n{rep.json()['message']}")
BaseException: Please report this, 400 - https://www.speedrun.com/api/v1/leaderboards/76rg9l18/category/ndx8p5rk
The selected category is for individual-level runs, but no level was selected.```

**Comment by GB127** [comment]
Oh woops forgot about that part. Thank you for the report!

**Comment by GB127** [comment]
I'll try to tackle this in the next days. I've isoled some stuffs that I need to do, but I need to determine how I want to approach.

**Comment by GB127** [comment]
Ended up doing it right away, as I suddenly got an idea. Should be fixed...

**Comment by GB127** [comment]
@shenef  How should I write the full "name"?

Currently it's something like :
{GAME} - {LEVEL} - {Category}

I'm thinking about something like
{GAME}, level {LEVEL} - {Category}

Have ideas?

**Comment by shenef** [comment]
ILs seem to work fine now, found one error but i'll submit that as a separate issue

I already like the current 
`Initializing {GAME} - {LEVEL} - {Category}'s  leaderboard data`
but i'd shorten it to
`Initializing {GAME} - {LEVEL} - {Category}`
Could "Initializing" be replaced by "Fetching" or would that be wrong?

Adding a "level" sometimes won't fit, since some leaderboards don't actually use it for "levels" but also for boss rushes or challenges.

**Comment by GB127** [comment]
Okay I did your suggestions, they make sense. :)

**Comment by GB127** [comment]
This is now relevant.
