### ISSUE TITLE
[feature idea] Cache runs locally to reduce requests

### ISSUE THREAD

**Issue by shenef** [GB127/SRC-statistics#83]
Caching the data locally should drastically cut down on requests and the Time it takes to access the data.
To check which runs should be requested you could for example check the "Most recent run" date of a game and compare it to the date from runs of that game in the local database. (I don't know much about the srcom API, there is probably a better way to do that.)
A command line argument could be used to fully rebuild the local database for debugging and troubleshooting purposes.

**Comment by GB127** [comment]
My new way of doing requests have reduced the requests considerably. I still want to do some caching in order to abolish requests if reusing the script.

But for now, the number of requests should be much lower than before.

**Comment by GB127** [comment]
Reimplemented. Will wait 2 minutes if maximum reached. A bit long, but it should occur for users with really high quantity of runs...
